Fix signal kyco/core.shutdown
kytos/kytos pull request #102
Opened 2016-10-13 13:53 UTC by macartur

- Fix signal shutdown in core.napps.py
- Add private method _execute_loop to run execute method until the signal
'kyco/core.shutdown' is received.
- Remove unused comments.
- Fix #101

2016-10-13 14:33 UTC, macartur commented
After send a shutdown some times the thread can't stop. I will investigate it.

2016-10-18 11:09 UTC, macartur commented
@raphaelmcobe , I discovered the error, the package kyco-core-napps has a older implementation using signals with Classes and now we have a specific string to represent a signal. If you running locally all tests pass.

2016-10-26 18:32 UTC, cemsbr requested changes
I'm taking care of the requested changes.

2016-10-26 18:32 UTC, cemsbr commented on kyco/core/napps.py
> +        while(not self.__event.is_set()):
What if the user only want to run `execute()` once?

2016-10-26 19:08 UTC, cemsbr approved these changes

2016-10-27 13:32 UTC, merged