Add authentication to REST methods based on configuration option
kytos/kytos pull request #1141
Opened 2020-08-26 13:38 UTC by ajoaoff

Users can configure kytos to add configuration to REST methods. This PR does the following:

- remove unecessary `rest` import in `kytos.core.helpers`;
- add configuration option `authenticate_urls`;
- decorate defined methods with `authenticated` before registering in Flask.

The configuration is based on URLs, so if any URL a method is registered to matches `authenticate_urls`, the method will
enforce authentication.
An endpoint URL is considered to match `authenticate_urls` if any URL defined there is a substring of the endpoint URL.
For example, assume `authenticate_urls = ["kytos/mef_eline", "pathfinder"]`, then:
- `/api/kytos/mef_eline/1` matches;
- `/api/kytos/pathfinder` matches;
- `/api/amlight/mef_eline` does not match;
- `/api/amlight/pathfinder` matches.

2020-09-24 16:32 UTC, hdiogenes requested changes

2020-09-24 16:32 UTC, hdiogenes commented on kytos/core/api_server.py
> +           that function will require authentication.
```suggestion
        If any URL marked for authentication uses a function,
        that function will require authentication.
```

2020-09-24 16:32 UTC, hdiogenes commented on kytos/core/config.py
> +            )
```suggestion
            authenticate_urls)
```

2020-09-24 16:32 UTC, hdiogenes commented on kytos/templates/kytos.conf.template
> +# Define urls to be authenticated
```suggestion
# Define URLs that will require authentication
```

2020-09-24 16:32 UTC, hdiogenes commented on kytos/core/api_server.py
> +                   function.authenticated:
```suggestion
                if getattr(function, 'authenticated', False):
```

2020-09-24 16:32 UTC, hdiogenes commented on kytos/core/config.py
> +                    'authenticate_urls': '[]',
Why were those two default values removed?

2020-09-24 17:10 UTC, ajoaoff commented on kytos/core/config.py
> +                    'authenticate_urls': '[]',
Acho que não deveriam ter sido removidos, não lembro porque fiz isso.

2020-09-30 18:29 UTC, ajoaoff commented
I found a bug. Do not accept it yet.

2020-10-15 16:46 UTC, hdiogenes approved these changes

2020-10-15 19:00 UTC, hdiogenes commented on kytos/templates/kytos.conf.template
> +# This must a be a list of part of URLs. For example, if "kytos/mef_eline"
```suggestion
# This must be a list of part of URLs. For example, if "kytos/mef_eline"
```

2020-10-15 19:01 UTC, hdiogenes commented on kytos/core/api_server.py
> +                inner = function
```suggestion
            inner = getattr(function, '__func__', function)
```

2020-10-21 20:03 UTC, merged