Create config field in Interface
kytos/kytos pull request #1142
Opened 2020-08-27 17:31 UTC by gleybersonandrade

This PR creates a new 'config' field on Interface class. This field can assume one of the following values from Port or PhyPort classes:

OFPPC_PORT_DOWN: Port is administratively down;
OFPPC_NO_RECV: Drop all packets received by port;
OFPPC_NO_FWD: Drop packets forwarded to port;
OFPPC_NO_PACKET_IN: Do not send packet-in msgs for port.

2020-08-27 19:10 UTC, gleybersonandrade commented
More info about these flags can be viewed on page 36 of Openflow 1.3 spec:

https://www.opennetworking.org/wp-content/uploads/2014/10/openflow-spec-v1.3.0.pdf

2020-09-01 11:59 UTC, ajoaoff commented
You stated that the field will assume one of the four values. In fact, each of the values is a bit, and the field can possibly have all of them set. For example, if the field has the value, in bits, `01000101`, then `OFPPC_NO_FWD` is `False` and the others are `True`.

2020-09-16 16:15 UTC, hdiogenes requested changes

2020-09-16 16:15 UTC, hdiogenes commented on kytos/core/interface.py
> +                by the switch.
```suggestion
            config(|port_config|): Port config used to indicate interface
                behavior. In general, the port config bits are set by the
                controller and are not changed by the switch. Options
                are: administratively down, ignore received packets, drop
                forwarded packets, and/or do not send packet-in messages.
```

2020-09-17 17:43 UTC, ajoaoff approved these changes

2020-09-24 14:48 UTC, merged

2020-10-12 15:30 UTC, italovalcy commented
Hi guys. THe PR seems to be very interesting for the switch management, in particular for those switches with special ports which does not support forwarding, packet_in, etc. I suppose this config should be changed only through OpenFlow PORT DESC messages, but not via Kytos REST API, right ? I'm asking this because I didn't see any modification on the REST API for this PR. If that is so, it makes sense to me.