Napp management refactor
kytos/kytos pull request #210
Opened 2017-01-10 14:57 UTC by diraol

- Adds the NApps directory into the system path, so we can access the napps as python libraries;
 - Improve the "Load Napp" method;
 - Adds "Enable" and "Disable" napps methods.

2017-01-10 17:30 UTC, beraldoleal requested changes

2017-01-10 17:30 UTC, beraldoleal commented on kyco/controller.py
> +        napp_abs_path = os.path.join(self.options.napps, '.installed',
this vars should be more global.

2017-01-10 17:30 UTC, beraldoleal commented on kyco/controller.py
> +
May be is more pythonic with try... except

2017-01-10 17:30 UTC, beraldoleal commented on kyco/config.py
> +sys.path.append(os.path.join(BASE_ENV, 'var/lib/kytos'))
`os.path.join(BASE_ENV, 'var/lib/kytos')` is already been used on many parts of code. Please make this a var or config.

2017-01-10 18:40 UTC, merged

2017-01-20 19:17 UTC, cemsbr commented
Note: build failed :(