Avoid multiple calls of NApp shutdown method
kytos/kytos pull request #235
Opened 2017-02-21 13:39 UTC by diraol

FIX #233

2017-02-23 03:35 UTC, cemsbr requested changes

2017-02-23 03:35 UTC, cemsbr commented on kyco/core/napps.py
> +            self.__shutdown_already_called = True
Can we avoid creating a new variable by using the event itself like below?
```python
if not self.__event.is_set():
    self.__event.set()
    self.shutdown()
```

2017-02-24 17:17 UTC, beraldoleal commented on kyco/core/napps.py
> +            self.__shutdown_already_called = True
@diraol  ?

2017-02-24 17:22 UTC, diraol commented on kyco/core/napps.py
> +            self.__shutdown_already_called = True
Done as requested. I liked  the suggestion @cemsbr

2017-02-24 17:28 UTC, merged