WIP: Merge kytos-admin-ui
kytos/kytos pull request #280
Opened 2017-03-27 14:20 UTC by renanrodrigo

1. Merged kytos-admin-ui as suggested by @diraol in #269 
2. Changed Flask root dir, adding routes to serve the index.html file
3. Manually precompiled the style.css file

2017-03-27 19:22 UTC, diraol commented
@renanrodrigo have you tested? The web-ui is running? How did you tested it?

2017-03-27 19:28 UTC, renanrodrigo commented
I tested it by running:
1. `kytosd`
2. `firefox localhost:8181`

And it shows the homepage. I didn't write any test for this though.

2017-03-27 19:39 UTC, beraldoleal submitted a review, later dismissed

2017-03-27 19:39 UTC, beraldoleal commented on .gitignore
> +#kytos/web-ui/source/static/css/*
Static css, ideally should be compiled and we should not commit. But maybe we have some "custom" hardcorded css. Can you check if all files here are compiled via sass/less ?

2017-03-27 19:47 UTC, renanrodrigo commented
The comment will be removed ASAP. Just need to remember to compile the Sass after running setup.py then. Will do.

2017-03-27 20:56 UTC, renanrodrigo commented
@beraldoleal done. Looks like everything is in order.

2017-03-28 18:03 UTC, diraol commented
@renanrodrigo 
What I have done:
1) Created a new clean virtualenv and activated it;
2) Installed the latest version of python-openflow (and its dependencies) with python setup.py install (python3.6);
3) Installed the latest version of kytos-utils (and its dependencies) with python setup.py install (python3.6);
4) Tried to install kytos from your branch (renanrodrigo:merge_webui) with python setup.py install (python3.6).

I got the following error on step 4. Can you take a look at it:
```
running install
running bdist_egg
running egg_info
writing kytos.egg-info/PKG-INFO
writing dependency_links to kytos.egg-info/dependency_links.txt
writing requirements to kytos.egg-info/requires.txt
writing top-level names to kytos.egg-info/top_level.txt
reading manifest file 'kytos.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'kytos.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying kytos/core/api_server.py -> build/lib/kytos/core
copying kytos/core/core.py -> build/lib/kytos/core
copying kytos/core/napps.py -> build/lib/kytos/core
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/tests
creating build/bdist.linux-x86_64/egg/tests/test_core
copying build/lib/tests/test_core/__init__.py -> build/bdist.linux-x86_64/egg/tests/test_core
copying build/lib/tests/test_core/test_tcp_server.py -> build/bdist.linux-x86_64/egg/tests/test_core
copying build/lib/tests/test_core/test_interface.py -> build/bdist.linux-x86_64/egg/tests/test_core
creating build/bdist.linux-x86_64/egg/kytos
copying build/lib/kytos/__init__.py -> build/bdist.linux-x86_64/egg/kytos
creating build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/tcp_server.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/api_server.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/__init__.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/buffers.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/helpers.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/core.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/napps_manager.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/constants.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/napps.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/events.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/daemon.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/switch.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/controller.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/flow.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/config.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/exceptions.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/websocket.py -> build/bdist.linux-x86_64/egg/kytos/core
byte-compiling build/bdist.linux-x86_64/egg/tests/test_core/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_core/test_tcp_server.py to test_tcp_server.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_core/test_interface.py to test_interface.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/tcp_server.py to tcp_server.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/api_server.py to api_server.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/buffers.py to buffers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/helpers.py to helpers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/core.py to core.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/napps_manager.py to napps_manager.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/constants.py to constants.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/napps.py to napps.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/events.py to events.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/daemon.py to daemon.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/switch.py to switch.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/controller.py to controller.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/flow.py to flow.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/config.py to config.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/exceptions.py to exceptions.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/websocket.py to websocket.cpython-36.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating /home/diraol/.virtualenvs/kytos/etc/kytos
copying etc/kytos.conf -> /home/diraol/.virtualenvs/kytos/etc/kytos
copying etc/logging.ini -> /home/diraol/.virtualenvs/kytos/etc/kytos
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/kytosd -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/kytosd to 755
copying kytos.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/kytos-2017.1b1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing kytos-2017.1b1-py3.6.egg
creating /home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg
Extracting kytos-2017.1b1-py3.6.egg to /home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages
Adding kytos 2017.1b1 to easy-install.pth file
Installing kytosd script to /home/diraol/.virtualenvs/kytos/bin

Installed /home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg
Processing dependencies for kytos==2017.1b1
Searching for python-daemon>=2.1.2
Reading https://pypi.python.org/simple/python-daemon/
Downloading https://pypi.python.org/packages/b2/fb/a280d65f81e9d69989c8d6c4e0bb18d7280cdcd6d406a2cc3f4eb47d4402/python-daemon-2.1.2.tar.gz#md5=9c57343d81f2a96c51cffeab982b04d2
Best match: python-daemon 2.1.2
Processing python-daemon-2.1.2.tar.gz
Writing /tmp/easy_install-24ql21q6/python-daemon-2.1.2/setup.cfg
Running python-daemon-2.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-24ql21q6/python-daemon-2.1.2/egg-dist-tmp-3vwmxi27
Traceback (most recent call last):
  File "/home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/setuptools/dist.py", line 414, in fetch_build_egg
    cmd = self._egg_fetcher
AttributeError: 'ChangelogAwareDistribution' object has no attribute '_egg_fetcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/diraol/.virtualenvs/kytos/lib/python3.6/site-pack [...]

2017-03-28 18:04 UTC, diraol requested changes
@renanrodrigo 
What I have done:
1) Created a new clean virtualenv and activated it;
2) Installed the latest version of python-openflow (and its dependencies) with python setup.py install (python3.6);
3) Installed the latest version of kytos-utils (and its dependencies) with python setup.py install (python3.6);
4) Tried to install kytos from your branch (renanrodrigo:merge_webui) with python setup.py install (python3.6).

I got the following error on step 4. Can you take a look at it:
```
running install
running bdist_egg
running egg_info
writing kytos.egg-info/PKG-INFO
writing dependency_links to kytos.egg-info/dependency_links.txt
writing requirements to kytos.egg-info/requires.txt
writing top-level names to kytos.egg-info/top_level.txt
reading manifest file 'kytos.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'kytos.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying kytos/core/api_server.py -> build/lib/kytos/core
copying kytos/core/core.py -> build/lib/kytos/core
copying kytos/core/napps.py -> build/lib/kytos/core
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/tests
creating build/bdist.linux-x86_64/egg/tests/test_core
copying build/lib/tests/test_core/__init__.py -> build/bdist.linux-x86_64/egg/tests/test_core
copying build/lib/tests/test_core/test_tcp_server.py -> build/bdist.linux-x86_64/egg/tests/test_core
copying build/lib/tests/test_core/test_interface.py -> build/bdist.linux-x86_64/egg/tests/test_core
creating build/bdist.linux-x86_64/egg/kytos
copying build/lib/kytos/__init__.py -> build/bdist.linux-x86_64/egg/kytos
creating build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/tcp_server.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/api_server.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/__init__.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/buffers.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/helpers.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/core.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/napps_manager.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/constants.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/napps.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/events.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/daemon.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/switch.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/controller.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/flow.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/config.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/exceptions.py -> build/bdist.linux-x86_64/egg/kytos/core
copying build/lib/kytos/core/websocket.py -> build/bdist.linux-x86_64/egg/kytos/core
byte-compiling build/bdist.linux-x86_64/egg/tests/test_core/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_core/test_tcp_server.py to test_tcp_server.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/tests/test_core/test_interface.py to test_interface.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/tcp_server.py to tcp_server.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/api_server.py to api_server.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/buffers.py to buffers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/helpers.py to helpers.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/core.py to core.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/napps_manager.py to napps_manager.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/constants.py to constants.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/napps.py to napps.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/events.py to events.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/daemon.py to daemon.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/switch.py to switch.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/controller.py to controller.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/flow.py to flow.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/config.py to config.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/exceptions.py to exceptions.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/kytos/core/websocket.py to websocket.cpython-36.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating /home/diraol/.virtualenvs/kytos/etc/kytos
copying etc/kytos.conf -> /home/diraol/.virtualenvs/kytos/etc/kytos
copying etc/logging.ini -> /home/diraol/.virtualenvs/kytos/etc/kytos
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/kytosd -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/kytosd to 755
copying kytos.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kytos.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/kytos-2017.1b1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing kytos-2017.1b1-py3.6.egg
creating /home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg
Extracting kytos-2017.1b1-py3.6.egg to /home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages
Adding kytos 2017.1b1 to easy-install.pth file
Installing kytosd script to /home/diraol/.virtualenvs/kytos/bin

Installed /home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/kytos-2017.1b1-py3.6.egg
Processing dependencies for kytos==2017.1b1
Searching for python-daemon>=2.1.2
Reading https://pypi.python.org/simple/python-daemon/
Downloading https://pypi.python.org/packages/b2/fb/a280d65f81e9d69989c8d6c4e0bb18d7280cdcd6d406a2cc3f4eb47d4402/python-daemon-2.1.2.tar.gz#md5=9c57343d81f2a96c51cffeab982b04d2
Best match: python-daemon 2.1.2
Processing python-daemon-2.1.2.tar.gz
Writing /tmp/easy_install-24ql21q6/python-daemon-2.1.2/setup.cfg
Running python-daemon-2.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-24ql21q6/python-daemon-2.1.2/egg-dist-tmp-3vwmxi27
Traceback (most recent call last):
  File "/home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/setuptools/dist.py", line 414, in fetch_build_egg
    cmd = self._egg_fetcher
AttributeError: 'ChangelogAwareDistribution' object has no attribute '_egg_fetcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diraol/.virtualenvs/kytos/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/home/diraol/.virtualenvs/kytos/lib/python3.6/site-pack [...]

2017-03-28 18:35 UTC, renanrodrigo commented
Will re-run the steps here and update ASAP

2017-03-28 19:07 UTC, renanrodrigo commented
@diraol well, I did the same thing and got the same error. 
But it's related to the installation of python-daemon, not related to any change I made.
Try to do the same you did, but using the master branch of the kytos/kytos repo. I got exactyl the same output.

2017-03-29 17:05 UTC, diraol commented
This PR is waiting for the solution of #288, that may be solved by #290. Despite the fact that it will still keep the #291 openned.

2017-03-30 15:48 UTC, diraol commented
Now waiting for #294, that fixes #293.
@renanrodrigo despite this small problem, I have installed your branch version but I still can not access the web_ui while running `kytosd -f`. Kytos itself is working fine (I tested it with mininet), but when accessing http://localhost:8181 I only get 404 error =/

2017-03-30 17:34 UTC, renanrodrigo commented
@diraol geesh...A line had been missing in setup.py. Just added it again.

2017-03-30 17:47 UTC, diraol approved these changes

2017-03-30 19:11 UTC, beraldoleal commented
@renanrodrigo @diraol Scrutinizer ?

2017-03-30 19:20 UTC, diraol commented
@beraldoleal the broken build is related to kytos/python-openflow#338.

Or we upload a new version of `python-openflow` on pypi with the fix for this error, or we change scrutinizer setup in order to get the latest version of `python-openflow` from the git repository.

@cemsbr these are the options, right?

2017-04-04 15:02 UTC, renanrodrigo commented
Re-merged the Kytos master here, seems to be alright now

2017-04-04 15:17 UTC, diraol commented
@renanrodrigo not anymore rs sorry...

2017-04-04 16:28 UTC, merged