Fix python-daemon install bug
kytos/kytos pull request #290
Opened 2017-03-28 22:19 UTC by cemsbr

This is an upstream bug that was solved by forking it.
Fix #288

2017-03-28 23:37 UTC, beraldoleal reviewed
Do you forked ? Do you really think that this is a good idea? Who is going to maintain this updated ?

2017-03-29 15:18 UTC, cemsbr commented
Yes, I forked and I think it was a good idea because upstream has had this issue unfixed for 4 months. When upstream releases the next version, it will be used automatically because our requirement is ">=2.1.2".

2017-03-29 15:31 UTC, beraldoleal commented
@cemsbr did you submitted a PR to upstream too ? I think that this is important.

2017-03-29 15:34 UTC, beraldoleal commented
I'm going to accept. But we have to pay attention to this in order to revert this on near future.

2017-03-29 17:01 UTC, diraol requested changes
@cemsbr, run python setup.py test before re-sending this PR, I think that there are some other [isort] errors. At least, after adding the `#noqa` here locally, the tests passed on this URL line but they broke on other files because of isort errors.

2017-03-29 17:01 UTC, diraol commented on setup.py
> +          'https://github.com/cemsbr/python-daemon/tarball/latest_release#egg=python-daemon-2.1.2'
Please, add `#noqa: E501` at the end of line 145.

2017-03-30 14:06 UTC, cemsbr commented
@beraldoleal , yes, I did it in [their issue tracker](https://pagure.io/python-daemon/issue/2). I'm also watching the project to know when a new version is released.

2017-03-30 14:07 UTC, cemsbr commented on setup.py
> +          'https://github.com/cemsbr/python-daemon/tarball/latest_release#egg=python-daemon-2.1.2'
Thanks, @diraol. I split the string so I don't need to ignore checks.

2017-03-30 14:18 UTC, diraol approved these changes

2017-03-30 14:37 UTC, beraldoleal commented
@cemsbr cool, thanks for that.

2017-03-30 14:37 UTC, merged