Create lockfile to assert single instance execution of kytosd
kytos/kytos pull request #360
Opened 2017-04-19 19:09 UTC by renanrodrigo

2017-04-19 19:41 UTC, renanrodrigo commented
Depends on #361

2017-04-20 12:49 UTC, beraldoleal requested changes

2017-04-20 12:49 UTC, beraldoleal commented on kytos/core/controller.py
> +LOCK_PATH = '/tmp/lockytos'
This should be configured on `/etc/kytos/kytos.conf`. And should have a default value to `/var/run/kytos.pid`

2017-04-20 12:49 UTC, beraldoleal commented on kytos/core/controller.py
> +            lockfile = open(LOCK_PATH, mode='x')
s/lockfile/pidfile/g

2017-04-20 12:49 UTC, beraldoleal commented on kytos/core/controller.py
> +                exit(1)
Replace 1 with a proper constant. For instance `os.EX_CANTCREAT`

2017-04-20 12:49 UTC, beraldoleal commented on kytos/core/controller.py
> +        os.remove(LOCK_PATH)
s/LOCK_PATH/PID_FILE/g.

Also you have to handle exceptions like `FileNotFoundError`

2017-04-20 14:57 UTC, renanrodrigo commented
Rebased and working

2017-04-20 17:29 UTC, merged