Fix #370 - jinja2 on setup
kytos/kytos pull request #372
Opened 2017-04-24 20:40 UTC by diraol

2017-04-24 20:57 UTC, cemsbr requested changes

2017-04-24 20:57 UTC, cemsbr commented on setup.py
> +            if PurePosixPath(path).stem == 'site-packages':
We can use `Path` here to have a shorter import and a more portable code.

2017-04-24 20:57 UTC, cemsbr commented on setup.py
> +        jinja2path = site_pkg.glob('Jinja2*').__next__()
`next(site_pkg.glob('Jinja2*'))`

2017-04-25 13:04 UTC, diraol commented on setup.py
> +            if PurePosixPath(path).stem == 'site-packages':
I thought (because of the documentation) that Path didn't had the stem property. I've checked and it have, so I'm changing it.

2017-04-25 13:18 UTC, beraldoleal commented on setup.py
> +        from jinja2 import Template  # pylint: disable=import-error
```
try:
  from jinja2 import Template
except ImportErrorBlabal:
  ...add_jinja2_to_path()
```

2017-04-25 13:35 UTC, merged