Improving logs
kytos/kytos pull request #377
Opened 2017-04-26 15:25 UTC by macartur

Set logging configuration using  etc/kytos/logging.ini
Fixed syslog

2017-04-26 16:58 UTC, diraol requested changes

2017-04-26 16:58 UTC, diraol commented on etc/kytos/logging.ini
> +args: ['/dev/log']
@macartur this should be `/var/log` doesn't it?

2017-04-26 16:58 UTC, diraol commented on kytos/core/logs.py
> +        handler.setFormatter(Formatter(FORMAT))
Can't you retrieve the format from one of those defined on the `logging.ini` file?

2017-04-26 21:07 UTC, macartur commented on etc/kytos/logging.ini
> +args: ['/dev/log']
This is the device used to write in local syslog. I will try to change this.

2017-04-28 14:40 UTC, macartur commented on etc/kytos/logging.ini
> +args: ['/dev/log']
I am using that http://scottbarnham.com/blog/2008/01/01/sysloghandler-not-writing-to-syslog-with-python-logging/, I can use syslog using logging.ini yet.

2017-05-02 14:52 UTC, cemsbr commented on etc/kytos/logging.ini
> +args: ['/dev/log']
I just noticed that I have /dev/log :). I did a quick read in the link above and also in Python's docs and I thinks it's ok.

2017-05-02 14:57 UTC, diraol commented on etc/kytos/logging.ini
> +args: ['/dev/log']
Agreed!

2017-05-02 14:59 UTC, diraol commented
@macartur also do not forget to mention which issue you are dealing with on you commit(s) message(s) =)

2017-05-02 15:56 UTC, beraldoleal commented
@macartur waiting for reply on @diraol comment.

2017-05-03 15:50 UTC, diraol approved these changes

2017-05-03 17:48 UTC, merged