Fixing template prefix when BASE_ENV is '/'
kytos/kytos pull request #403
Opened 2017-05-08 17:06 UTC by macartur

2017-05-08 18:11 UTC, beraldoleal commented
Duplicated of #402 ?

2017-05-09 15:58 UTC, erickvermot commented
@macartur is right, #402 still outputs double slashes when BASE_ENV is '/'. I'll close #402, this is a better solution.

2017-05-10 12:29 UTC, diraol approved these changes

2017-05-11 18:07 UTC, cemsbr approved these changes

2017-05-11 18:08 UTC, beraldoleal requested changes

2017-05-11 18:08 UTC, beraldoleal commented on etc/kytos/kytos.conf.template
> +napps = {{ prefix }}var/lib/kytos/napps
When we read things like this looks odd. I prefer `{{ prefix }}/var/lib/kytos/napps`. In order to do this, we have to make sure that prefix is something without a ending slash or something empty.

So if prefix == / lets make prefix == "". And additionally read my next comment.

2017-05-11 18:08 UTC, beraldoleal commented on setup.py
> +
Based on the previous comment, lets do the oposite. If prefix ends with '/' lets remove the last '/'.

2017-05-18 14:51 UTC, beraldoleal commented
@macartur ?

2017-05-19 13:41 UTC, macartur commented
@beraldoleal  Fixed.

2017-05-19 13:42 UTC, merged