Catching SystemExit before start the kytos' shell
kytos/kytos pull request #426
Opened 2017-05-16 20:18 UTC by macartur

Avoid start Kytos' Shell when thrown exception while starting the controller.

Fix #408

2017-05-18 13:41 UTC, beraldoleal requested changes

2017-05-18 13:41 UTC, beraldoleal commented on bin/kytosd
> +            sys.exit()
Please print some useful information when exiting... for instance the reason of SystemExit exception.

2017-05-22 18:18 UTC, diraol approved these changes

2017-05-23 14:06 UTC, beraldoleal requested changes

2017-05-23 14:06 UTC, beraldoleal commented on bin/kytosd
> +                print('Kytos daemon started.')
This should be a log right ?

2017-05-23 14:06 UTC, beraldoleal commented on bin/kytosd
> +            print("Kytos start aborted.")
Can this be a log ?

2017-05-23 14:06 UTC, beraldoleal commented on kytos/core/controller.py
> +                error_msg = ("PID file {} exists. Delete it if Kytos is not "
Why did you removed self.log.error ? This should be logged too.

2017-05-23 14:06 UTC, beraldoleal commented on kytos/core/controller.py
> -                sys.exit()
Here too

2017-05-23 14:24 UTC, macartur commented on bin/kytosd
> +            print("Kytos start aborted.")
Yes, I will change this.

2017-05-23 14:26 UTC, macartur commented on kytos/core/controller.py
> +                error_msg = ("PID file {} exists. Delete it if Kytos is not "
This message is logged too, when the SystemExit is raised the error message is given and the controller will display this in the log.

2017-05-23 14:30 UTC, merged