Do not disable any logger
kytos/kytos pull request #430
Opened 2017-05-18 21:38 UTC by cemsbr

Fix #386

List of loggers that *were* disabled:
- concurrent.futures logger
- kytos.core.buffers logger
- kytos.core.napps.manager logger
- kytos.core.switch logger
- kytos.core.tcp_server logger
- socketio logger

2017-05-19 12:57 UTC, beraldoleal requested changes

2017-05-19 12:57 UTC, beraldoleal commented on kytos/core/logs.py
>              config.fileConfig(cls.configuration)
Should not the line be here too?

2017-05-19 18:15 UTC, cemsbr commented on kytos/core/logs.py
>              config.fileConfig(cls.configuration)
good catch. I refactored not to repeat code.

2017-05-19 18:16 UTC, diraol approved these changes

2017-05-19 18:39 UTC, macartur requested changes

2017-05-19 18:39 UTC, macartur commented on kytos/core/logs.py
> -            cls.configuration.set('handler_syslog', 'args', '[]')
I guess you forgot to verify the handler_syslog. This line change the 'handler_syslog' if the file /dev/syslog don't exists.

2017-05-20 18:09 UTC, cemsbr commented
@beraldoleal and @macartur, I believe all the issues are solved now. There's also tests for this issues and 100% coverage of logs module.

2017-05-22 13:21 UTC, merged