Adding NAppsDirListener to observe napps changes
kytos/kytos pull request #484
Opened 2017-06-26 20:29 UTC by macartur

Fix  #476

2017-06-26 21:10 UTC, cemsbr commented on kytos/core/controller.py
> +        self.napp_dir_listener.start()
To avoid concurrency problems, start it before load_napps().

2017-06-26 21:10 UTC, cemsbr commented on kytos/core/controller.py
> +        self.log.info(napp)
We already have log messages in the `if else` below. Is this one necessary?

2017-06-26 21:10 UTC, cemsbr commented on kytos/core/napps/napps_dir_listener.py
> +        log.info(relative_path)
I believe this is a debugging message.

2017-06-26 21:10 UTC, cemsbr commented on kytos/core/napps/napps_dir_listener.py
> +        self._controller.load_napp(*napp)
Log as info that the napp was enabled before calling controller.

2017-06-26 21:10 UTC, cemsbr commented on kytos/core/napps/napps_dir_listener.py
> +        self._controller.unload_napp(*napp)
Log as info that the napp was disabled before calling controller.

2017-06-27 15:56 UTC, cemsbr approved these changes

2017-06-30 13:37 UTC, diraol requested changes

2017-06-30 13:37 UTC, diraol commented on CHANGELOG.rst
> +- Added NAppDirListener class to manager napps when enabled or disabled by
`NAppDirListener to listen to NApps that were enabled/disabled by kytos-utils and then load/unload them on the current running controller.`

2017-06-30 13:37 UTC, diraol commented on kytos/core/controller.py
> +        #: Observer that handle napps changes.
`Observer that handle NApps when they are enabled or disabled.`

2017-06-30 13:37 UTC, diraol commented on kytos/core/napps/napps_dir_listener.py
> +        log.info('The NApp "%s/%s" was enabled.', *napp)
I don't think we need this log here, since the `controller.load_napp` will do the proper logging procedure...
May be just a debug message.

2017-06-30 13:37 UTC, diraol commented on kytos/core/napps/napps_dir_listener.py
> +        log.info('The NApp "%s/%s" was disabled.', *napp)
I don't think we need this log here, since the `controller.load_napp` will do the proper logging procedure...
May be just a debug message.

2017-06-30 13:37 UTC, diraol commented on tests/test_core/test_napp_dir_listener.py
> +        self.napp_dir_listener.on_created(self.event)
@cemsbr is this test ok? Shouldn't we test this by creating a directory under the 'napps_dir' (mocked) to see the event being dispatched by the observer?

2017-06-30 17:12 UTC, cemsbr commented on tests/test_core/test_napp_dir_listener.py
> +        self.napp_dir_listener.on_created(self.event)
We can make tests simpler by assuming watchdog works and that it will call the appropriate method.

2017-07-03 14:09 UTC, diraol approved these changes

2017-07-03 14:42 UTC, diraol requested changes

2017-07-03 14:42 UTC, diraol commented on kytos/core/napps/napps_dir_listener.py
> +        super(NAppDirListener, self).__init__()
Python new syntax....
```python
super().__init__()
```

2017-07-03 14:44 UTC, diraol commented
And do not forget to make the PR to both branches (``master`` and ``2017.1rc``)

2017-07-03 19:15 UTC, cemsbr requested changes
To be consistent, rename napps_dir_listener.py to napp_dir_listener.py (singular as in the class name).

2017-07-04 13:36 UTC, diraol approved these changes

2017-07-04 15:17 UTC, cemsbr approved these changes

2017-07-04 15:33 UTC, merged