Issue #441
kytos/kytos pull request #495
Opened 2017-07-02 16:13 UTC by macartur

2017-07-03 14:47 UTC, diraol commented
@macartur Please, use a better PR title and description.

And do not forget to do the PR to both `master` and `2017.1rc` branches.

2017-07-03 16:44 UTC, cemsbr requested changes
I wouldn't ignore D301, but use r""" where it happens. It is OK to rebase in this specific case. Please, write a comment like "Close #441" in a commit long description.

2017-07-04 14:08 UTC, diraol requested changes

2017-07-04 14:08 UTC, diraol commented on kytos/core/buffers.py
> +__all__ = ('KytosBuffers', 'KytosEventBuffer')
`KytosEventBuffer` was not supposed to be exposed.

2017-07-04 14:08 UTC, diraol commented on kytos/core/buffers.py
> +            event (:class:`~kytos.core.buffers.KytosEventBuffer`):
event is an instance of `KytosEvent`, a class from `kytos.core.events` module.

2017-07-04 14:08 UTC, diraol commented on kytos/core/buffers.py
> +            :class:`~kytos.core.buffers.KytosEventBuffer`:
This is not the correct class.
`kytos.core.buffers.KytosEventBuffer` != `kytos.core.events.KytosEvent`

2017-07-04 14:08 UTC, diraol commented on kytos/core/buffers.py
> +                KytosEventBuffer sent to queue.
Wrong here too.

2017-07-04 14:08 UTC, diraol commented on kytos/core/buffers.py
> +        """Method to send a ``kytos/core.shutdown`` event to all buffers."""
Since we are rewriting, let's go with:
`Send a ``kytos/core.shutdown`` event to each buffer.`

2017-07-04 14:08 UTC, diraol commented on kytos/core/switch.py
> +           datetime.datetime.now: Last time when the ethernetframe was flooded.
`s/ethernetframe/ethernet_frame/`

2017-07-04 14:08 UTC, diraol commented on kytos/core/tcp_server.py
> +                The controller instance.
`s/The controller instance/An instance of Kytos Controller class/`

2017-07-05 18:43 UTC, diraol approved these changes
I think that this is the best solution for now, despite some disadvantages. As we intend to remove all python-openflow dependencies from kytos, I recommend this PR to be accepted to solve some documentation/linter warnings and errors.

2017-07-06 13:41 UTC, merged