update docs/developer/hacking.rst
kytos/kytos pull request #539
Opened 2017-07-18 17:52 UTC by erickvermot

https://github.com/kytos/kytos/issues/536
I took what I thought was important from docs/hacking.rst

2017-07-18 18:19 UTC, diraol commented on docs/developer/hacking.rst
> +	    sudo python setup.py develop
@cemsbr what about `pip install -e .`? Should we focus on installation process using `pip` instead of `setup`? As far as I remember this has something to do with wheels, doesn't it?

2017-07-18 18:25 UTC, erickvermot commented on docs/developer/hacking.rst
> +	    sudo python setup.py develop
@diraol I have no idea if it has something to do with wheels... About the installation process, I believe it is not up to me to answer.

2017-07-18 19:06 UTC, cemsbr commented on docs/developer/hacking.rst
> +	    sudo python setup.py develop
pip is now required, so we can use it instead. However, I think they are behaving similarly.

2017-07-18 19:07 UTC, cemsbr commented on docs/developer/hacking.rst
> +	    sudo python setup.py develop
@erickvermot, you can find the installation process in the rest of the doc. Others have reviewed it.

2017-07-19 13:13 UTC, erickvermot commented on docs/developer/hacking.rst
> +	    sudo python setup.py develop
@cemsbr, I reviewed it on quickstart for ex.
Still see no reason not to call setup. Result is the same, pip use setuptools.
On this same page we call setup to do the tests for ex.
I made the changes anyway.

2017-07-19 19:09 UTC, cemsbr approved these changes

2017-07-22 13:43 UTC, diraol requested changes

2017-07-22 13:43 UTC, diraol commented on docs/developer/hacking.rst
> +the system locations. This allows developpers to quickly test changes made in
@erickvermot Sorry, I didn't see this type on the first review.
`s/developpers/developers`.

2017-07-22 13:43 UTC, diraol commented on docs/developer/hacking.rst
> +source code.
Another one I missed on the review. `changes made in source code` -> `changes made in the source code`.

2017-07-22 13:43 UTC, diraol commented on docs/developer/index.rst
> +
I would also add `hacking` prior to the `api` and the `listened_events`. It makes more sense, doesn't it?

2017-07-26 19:35 UTC, diraol approved these changes

2017-07-26 19:47 UTC, erickvermot commented
As requested by @diraol and @cemsbr, I joined the review commits with the original one and force pushed.

2017-07-26 19:50 UTC, merged