Dependency version management
kytos/kytos pull request #540
Opened 2017-07-18 18:40 UTC by macartur

- Move requirements*.txt to requirements folder
- Add pip-tools as dependency
- Change setup.py and tox.ini to use the requiements folder
- Update MANIFEST.in to include requirements/run.in and remove requirements*.txt
- Move requirements to setup.py
- Fix #537

2017-07-18 21:33 UTC, cemsbr approved these changes

2017-07-22 14:18 UTC, diraol commented
@macartur, please, rebase it.

2017-07-22 14:19 UTC, diraol requested changes
@macartur, please, rebase it.

2017-07-26 22:19 UTC, cemsbr commented
I rebased and added a commit in the PR above.

2017-07-27 19:10 UTC, closed without merging