Fix regex to download napp based on version.
kytos/kytos pull request #544
Opened 2017-07-21 13:30 UTC by macartur

2017-07-21 19:15 UTC, cemsbr approved these changes
Ok to use a dash because this is not a valid character for both username and NApp name.

2017-07-22 14:18 UTC, diraol approved these changes

2017-07-28 17:27 UTC, beraldoleal requested changes
I'm not sure if this will affect this PR but talking with @diraol and @cemsbr I would like to keep ":" as separator for versions. (Like docker).

Of course we can still use - to save our files.

But please keep in mind that our uri is with ":".

2017-08-01 13:35 UTC, macartur commented
I will close this PR because this change is unnecessary if we use ":" as a separator for versions.

2017-08-01 13:35 UTC, closed without merging