Improve kytos daemon
kytos/kytos pull request #605
Opened 2017-10-05 14:59 UTC by macartur

2017-10-05 15:17 UTC, diraol approved these changes

2017-10-05 15:47 UTC, diraol requested changes
Please, update the CHANGELOG !

2017-10-06 16:03 UTC, diraol submitted a review, later dismissed

2017-10-06 21:36 UTC, cemsbr approved these changes

2017-10-06 22:12 UTC, cemsbr requested changes

2017-10-06 22:12 UTC, cemsbr commented on kytos/core/daemon.py
> +            pass
This busy waiting is using 100% CPU.

2017-10-06 22:15 UTC, cemsbr requested changes
It's using 100% CPU.

2017-10-17 13:31 UTC, cemsbr requested changes

2017-10-17 13:31 UTC, cemsbr commented on kytos/core/daemon.py
> +            sleep(0.02)
Please, change to 0.5 and rebase.

2017-10-17 17:02 UTC, cemsbr approved these changes

2018-01-30 18:20 UTC, hdiogenes commented
Needs a description and/or linked issue. Improve the daemon in which ways?

2018-01-31 12:04 UTC, beraldoleal commented
@macartur please provide a better description.

2018-04-24 13:24 UTC, closed without merging