Create method to update the web-ui
kytos/kytos pull request #668
Opened 2017-12-12 17:20 UTC by macartur

This method can be called at the console or using utils via REST.
Fix kytos/kytos#666

2017-12-12 17:28 UTC, renanrodrigo approved these changes

2017-12-13 16:09 UTC, beraldoleal requested changes

2017-12-13 16:09 UTC, beraldoleal commented on kytos/core/api_server.py
> +            zip_ref.close()
Here if the file is corrupted or something goes wrong, we lost the directory.

We don't need to use github api for now, but at least:

1. download zip file.
2. try unzip in a temp folder, for instance: `kytos-ui.latest`
3. move old folder to `kytos-ui.20171231`
4. move temp folder to kytos-ui

2017-12-13 16:15 UTC, beraldoleal requested changes

2017-12-13 16:15 UTC, beraldoleal commented on kytos/core/api_server.py
> +        self.register_core_endpoint('update_ui/', self.update_web_ui)
I would prefer like that: web/update

2017-12-14 12:38 UTC, merged