[CHANGELOG] Update to release 2018.1b1
kytos/kytos pull request #698
Opened 2018-03-08 19:57 UTC by macartur

2018-03-08 21:13 UTC, renanrodrigo requested changes

2018-03-08 21:13 UTC, renanrodrigo commented on CHANGELOG.rst
> +- Added link attribute to the Interface class
Added: should be above

2018-03-08 21:13 UTC, renanrodrigo commented on CHANGELOG.rst
> +- Small refactore of Switch class.
s/refactore/refactor/g

2018-03-08 21:13 UTC, renanrodrigo commented on CHANGELOG.rst
> +- Add 'active' and 'enabled' flags to GenericEntity
GenericEntity itself was added in this version also

2018-03-09 13:35 UTC, beraldoleal requested changes

2018-03-09 13:35 UTC, beraldoleal commented on CHANGELOG.rst
> +- Added some new blueprints
Added some new blueprints (EP012, EP013 and EP014)

2018-03-09 13:35 UTC, beraldoleal commented on CHANGELOG.rst
> +- Added Interface metadata informations
- Now, we have few Entities inside the core (Switch, Interface and Link)
- Each Entity has metadata attribute (a dict)

2018-03-09 13:35 UTC, beraldoleal commented on CHANGELOG.rst
> +- The Kytos controller have a Link class
remove this.

2018-03-09 13:35 UTC, beraldoleal commented on CHANGELOG.rst
> +- Add 'active' and 'enabled' flags to GenericEntity
Added 'active' and 'enable' flags to GenericEntity (EP013)

2018-03-09 13:35 UTC, beraldoleal commented on CHANGELOG.rst
> +
- Now, kytosd is a python module, to make it easy to run with asyncio on the future;
- This pre-release implements EP013 and EP014 as discussed on our last Kytos Dev Meeting.

2018-03-09 14:07 UTC, merged