Create Kytos API Authentication blueprint
kytos/kytos pull request #955
Opened 2019-09-05 13:41 UTC by gleybersonandrade

2019-10-01 14:59 UTC, beraldoleal requested changes

2019-10-01 14:59 UTC, beraldoleal commented on docs/blueprints/EP018.rst
> +
@gleybersonandrade @cmagnobarbosa Please, can you use the new header model, proposed by @hdiogenes ?

2019-10-01 14:59 UTC, beraldoleal commented on docs/blueprints/EP018.rst
> +Today, all NApps rest endpoints that are created through decorator @rest are
REST in upper case

2019-10-01 14:59 UTC, beraldoleal commented on docs/blueprints/EP018.rst
> +these endpoints can change Napps behavior. If want to restrict this access,
If the developer want to...

2019-10-01 14:59 UTC, beraldoleal commented on docs/blueprints/EP018.rst
> +@rest('endpoint'). In this project, we propose the addition of a new decorator,
In this blueprint

2019-10-01 14:59 UTC, beraldoleal commented on docs/blueprints/EP018.rst
> +he must use the @authenticated decorator as shown:
he/she or a neutral pronoun.

2019-10-01 14:59 UTC, beraldoleal commented on docs/blueprints/EP018.rst
> +- GET /api/kytos/auth/v1/users/<user_id>/ - This endpoint lists a specific user.
Get details about a specific user.

2019-10-03 14:12 UTC, hdiogenes commented on docs/blueprints/EP018.rst
> +        -d '{"username":"babel42", "password":"youshallnotpass", “email”: “babel42@email.com”}'
Fix quotes: s/“email”/"email"/, etc.

2019-10-03 14:15 UTC, hdiogenes commented on docs/blueprints/EP018.rst
> +    @rest(‘endpoint’)
Fix quotes here

2019-10-08 14:14 UTC, beraldoleal approved these changes

2019-10-08 14:17 UTC, hdiogenes commented on docs/blueprints/EP018.rst
> +- `Create Kytos API Authentication blueprint <https://github.com/kytos/kytos/pull/955>`_
Move these links to the References, and add here any questions that are still being discussed, if any.

2019-10-08 14:49 UTC, merged