Create Authentication module
kytos/kytos pull request #966
Opened 2019-10-18 17:46 UTC by gleybersonandrade

2019-10-22 18:45 UTC, ajoaoff requested changes
The methods to manipulate the user database should themselves be used only by authenticated users. There should be a method to create an initial user on deploy, or through CLI on the server.

2019-10-31 13:58 UTC, ajoaoff requested changes
I believe `_list_users` and `_list_user` should also require an authenticated user.
The method to create the default user should not be called by `__init__` , because the default user will be recreated every time Kytos is started.

2019-11-28 14:25 UTC, hdiogenes approved these changes

2019-11-28 19:51 UTC, ajoaoff commented on kytos/core/auth.py
> +                }
An empty `box` is not an error, it means there is no user with the given uid.

2019-11-28 19:59 UTC, ajoaoff requested changes

2019-11-28 19:59 UTC, ajoaoff commented on kytos/core/auth.py
> +                }
An empty `box` is not an error, it means there is no user with the given uid.

2019-11-28 19:59 UTC, ajoaoff commented on kytos/core/auth.py
> +            if error or not box:
```suggestion
            if error:
```

2019-11-28 19:59 UTC, ajoaoff commented on kytos/core/auth.py
> +            else:
```suggestion
            elif not box:
                response = {
                    "answer": f'User with uid {uid} not found',
                    "code": HTTPStatus.NOT_FOUND.value
                }
            else:
```

2019-11-28 19:59 UTC, ajoaoff commented on kytos/core/auth.py
> +                }
Same as `_find_user`. Here maybe it would be better to check first if the user exists.

2019-11-29 13:27 UTC, ajoaoff approved these changes

2019-12-03 13:57 UTC, hdiogenes commented on kytos/core/config.py
> +        parser.add_argument('-C', '--create_superuser',
```suggestion
        parser.add_argument('-C', '--create-superuser',
```

2019-12-03 14:58 UTC, merged